In [1]:
from google.colab import drive
# 挂载谷歌云盘
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# 打开pad原始文件
reassign_path = '/content/drive/MyDrive/reassignment/transaction_grant.csv'

reassign_df = pd.read_csv(reassign_path)

<ipython-input-2-f9c261d232bc>:6: DtypeWarning: Columns (6,18,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  reassign_df = pd.read_csv(reassign_path)

In [3]:
len(reassign_df)

1740786

In [4]:
print(reassign_df.columns)

Index(['rf_id', 'file_id', 'cname', 'caddress_1', 'caddress_2', 'caddress_3',
       'caddress_4', 'reel_no', 'frame_no', 'convey_text', 'record_dt',
       'last_update_dt', 'page_count', 'purge_in', 'convey_ty',
       'employer_assign', 'or_name', 'exec_dt', 'ack_dt', 'title', 'lang',
       'appno_doc_num', 'appno_date', 'appno_country', 'pgpub_doc_num',
       'pgpub_date', 'pgpub_country', 'grant_doc_num', 'grant_date',
       'grant_country', 'ee_name', 'ee_address_1', 'ee_address_2', 'ee_city',
       'ee_state', 'ee_postcode', 'ee_country', 'index'],
      dtype='object')

1. 首先，处理一下ee_name及ee_information

In [5]:
# 计算exec_dt列中缺失值的个数
missing_values_count = reassign_df['ee_name'].isna().sum()
missing_values_count

0

In [6]:
# 对一个字段操作前的基本步骤：
# 指定的列
cols = ['ee_country', 'ee_state', 'ee_city', 'ee_postcode', 'ee_address_1', 'ee_address_2']

# 填充缺失值为空字符串，转换为字符串类型，并去除首尾空格
reassign_df[cols] = reassign_df[cols].fillna('').astype(str).apply(lambda x: x.str.strip())

reassign_df[cols].head()

,ee_country,ee_state,ee_city,ee_postcode,ee_address_1,ee_address_2
0,,KENTUCKY,"PADUCAH,",42001,,"P.O. BOX 1479,"
1,,,,,,
2,,,,,,
3,,ARIZONA,TEMPE,,,
4,GERMANY,,D-8500 NURNBERG 6,,SCHMAUSENBECKSTRASSE 86,

In [7]:
#1））补充ee_country；
import numpy as np
# 新建ee_country_full列，首先复制ee_country的值
reassign_df['ee_country_full'] = reassign_df['ee_country']

# 如果ee_country为空字符串且ee_state不为空字符串，填充"UNITED STATES"
reassign_df['ee_country_full'] = np.where(
    (reassign_df['ee_country_full'] == '') & (reassign_df['ee_state'] != ''),
    "UNITED STATES",
    reassign_df['ee_country_full']
)

# 替换"VIRGIN ISLANDS, U.S."为"UNITED STATES"
reassign_df['ee_country_full'] = reassign_df['ee_country_full'].replace("VIRGIN ISLANDS, U.S.", "UNITED STATES")
reassign_df[['ee_country_full','ee_country','ee_state','ee_city','ee_address_1','ee_address_2']].head(10)

,ee_country_full,ee_country,ee_state,ee_city,ee_address_1,ee_address_2
0,UNITED STATES,,KENTUCKY,"PADUCAH,",,"P.O. BOX 1479,"
1,,,,,,
2,,,,,,
3,UNITED STATES,,ARIZONA,TEMPE,,
4,GERMANY,GERMANY,,D-8500 NURNBERG 6,SCHMAUSENBECKSTRASSE 86,
5,JAPAN,JAPAN,,,,
6,ENGLAND,ENGLAND,,,,
7,UNITED STATES,,CALIFORNIA,,,
8,SWEDEN,SWEDEN,,VASTERAS,,
9,UNITED STATES,,NEW YORK,NEW YORK,115 FIFTH AVENUE,

In [8]:
# 计算 ee_country_full 列中空字符串的数量
empty_string_count = (reassign_df['ee_country_full'] == '').sum()

# 打印结果
print(f"Number of empty strings in 'ee_country_full': {empty_string_count}")

Number of empty strings in 'ee_country_full': 9909

In [9]:
# 如果需要，保存拼接后的表到新的CSV文件
reassign_df.to_csv('/content/drive/MyDrive/reassignment/reassignment_grant_eeinfor.csv', index=False)